# Generated by Django 5.0.6 on 2024-06-04 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_hashtag_post_hashtags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hashtag',
            options={'verbose_name': 'Hashtag', 'verbose_name_plural': 'Hashtags'},
        ),
    ]
