# Generated by Django 5.0.6 on 2024-05-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_post_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='post', verbose_name='썸네일 이미지'),
        ),
    ]
