# Generated by Django 5.0.6 on 2024-05-30 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_posts_thumbnail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
