# Generated by Django 5.0.6 on 2024-06-20 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraping", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="phone_number",
            field=models.CharField(
                default="010-1234-1234",
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        regex="^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})$"
                    )
                ],
            ),
            preserve_default=False,
        ),
    ]
