# Generated by Django 5.0.6 on 2024-06-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "restaurant_name",
                    models.CharField(max_length=100, verbose_name="식당 이름"),
                ),
                (
                    "restaurant_address",
                    models.CharField(
                        max_length=100, null=True, verbose_name="식당 주소"
                    ),
                ),
                ("review_count", models.PositiveIntegerField(verbose_name="리뷰 개수")),
                ("category", models.CharField(max_length=100, verbose_name="카테고리")),
                (
                    "star_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, null=True, verbose_name="별점"
                    ),
                ),
                ("thumbnail_image", models.URLField(null=True, verbose_name="썸네일")),
                (
                    "current_state",
                    models.CharField(
                        max_length=100, null=True, verbose_name="영업 상태"
                    ),
                ),
            ],
            options={
                "db_table": "restaurant",
            },
        ),
    ]
