# Generated by Django 5.0.6 on 2024-06-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraping", "0005_alter_restaurant_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="phone_number",
            field=models.CharField(max_length=15, null=True, verbose_name="전화번호"),
        ),
    ]
