# Generated by Django 5.0.6 on 2024-06-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraping", "0006_alter_restaurant_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="thumbnail_image",
            field=models.URLField(max_length=500, null=True, verbose_name="썸네일"),
        ),
    ]
